[book]
authors = ["Laurent Carri√©"]
language = "en"
multilingual = false
src = "src"
title = "my songbook"


[output.html]
#mathjax-support = true
#additional-css = ["dtmo.css", "mermaid.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
default-theme = "rust"
preferred-dark-theme = "navy"

#[output.html.redirect]

[preprocessor.mermaid]
command = "mdbook-mermaid"
